### ISSUE TITLE
Error when restarting pod

### ISSUE THREAD

**Issue by mi8m** [ashleykleynhans/kohya-docker#14]
It starts fine, but when closing and reopening with application manager it throws this error:
tail: /workspace/logs/kohya_ss.log: file truncated
venv folder does not exist. Not activating...
Traceback (most recent call last):
  File "/workspace/kohya_ss/setup/validate_requirements.py", line 18, in <module>
    from kohya_gui.custom_logging import setup_logging
  File "/workspace/kohya_ss/kohya_gui/custom_logging.py", line 6, in <module>
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'
Validation failed. Exiting...
tail: /workspace/logs/kohya_ss.log: file truncated
venv folder does not exist. Not activating...
Traceback (most recent call last):
  File "/workspace/kohya_ss/setup/validate_requirements.py", line 18, in <module>
    from kohya_gui.custom_logging import setup_logging
  File "/workspace/kohya_ss/kohya_gui/custom_logging.py", line 6, in <module>
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'
Validation failed. Exiting...

**Comment by ashleykleynhans** [comment]
Thanks for raising this issue, should be fixed in the latest docker images:

* `ashleykza/kohya:24.1.4.post2`
* `ashleykza/kohya:latest`

**Comment by mi8m** [comment]
yup, working fine now, thx and wow you're fast
